
project_id = "jplkrysolselfculqvqr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[functions]
[functions.analyze-gym-photo]
verify_jwt = true
[functions.generate-workout-plan]
verify_jwt = true
