// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrdfzxedbgnxzqgayubv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyZGZ6eGVkYmdueHpxZ2F5dWJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NTM5OTQsImV4cCI6MjA3MTIyOTk5NH0.tgrCOmQkxbqB7RgQcIZ8RzbKwjQHZrqeX2ej1Prf2c0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export const checkAuthSession = async () => {
  const { data: { session } } = await supabase.auth.getSession();
  return session;
};