
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jplkrysolselfculqvqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwbGtyeXNvbHNlbGZjdWxxdnFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDQ3MjgsImV4cCI6MjA2MjM4MDcyOH0.ONBqZ01vHMrxEzxPklhPm5BlhI6O5Kjv1MFOJx_JN4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'implicit'
    }
  }
);

// Helper functions for debugging session issues
export const checkAuthSession = async () => {
  try {
    const { data, error } = await supabase.auth.getSession();
    console.log('Current session status:', {
      hasSession: !!data.session, 
      error: error?.message || null,
      sessionExpiresAt: data.session?.expires_at,
      currentTime: Math.floor(Date.now() / 1000)
    });
    return data.session;
  } catch (err) {
    console.error('Error checking auth session:', err);
    return null;
  }
}
